image: python:alpine

before_script:
  - pip install mkdocs mkdocs-material pygments jsx-lexer

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
